sudo: required

services:
  - docker

before_install:
  - docker build -t mahakagarwal248/client -f Dockerfile.dev .

script:
  - docker run -e CI=true mahakagarwal248/client npm test -- --coverage

after_success:
  #build production grade dockerfile
  - docker build -t mahakagarwal248/client .
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push mahakagarwal248/client
