version: '3'
services:
  server:
    image: mahakagarwal248/server
    ports: 
      - "5000:5000"
    environment: 
      - MONGO_URI=${MONGO_URI}
  client:
    build:
      dockerfile: DockerFile.dev
      context: ./
    depends_on: 
      - server
    volumes: 
      - ./node_modules:/client/node_modules
      - ./:/client
    stdin_open: true
    ports: 
      - "3000:3000"